import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildCodeowners, buildRegistry } from './lib/registry-builder.mts'

const CHECK_FLAG = '--check'
const CODEOWNERS_FLAG = '--codeowners'
const FALLBACK_OWNER = 'TommyBez'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const packageRoot = path.resolve(scriptDir, '..')
const repoRoot = path.resolve(packageRoot, '..', '..')
const agentsDir = path.join(repoRoot, 'registry')
const generatedDir = path.join(packageRoot, 'generated')
const codeownersPath = path.join(repoRoot, '.github', 'CODEOWNERS')

function createLoaderIndex(agentSlugs: readonly string[]): string {
  const entries = agentSlugs
    .map((slug) => `  '${slug}': () => import('./items/${slug}.json'),`)
    .join('\n')

  return `// Generated by scripts/generate-registry.mts — do not edit.
// One lazy loader per registry item: bundlers code-split each item's JSON
// into its own chunk, so serving one agent never loads the whole catalog's
// file contents into memory.
type ItemModule = { readonly default: unknown }

export const itemLoaders: Record<string, () => Promise<ItemModule>> = {
${entries}
}
`
}

function stringify(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

async function readFileIfExists(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, 'utf8')
  } catch {
    return null
  }
}

async function main(): Promise<void> {
  const isCheckOnly = process.argv.includes(CHECK_FLAG)
  const writeCodeowners = process.argv.includes(CODEOWNERS_FLAG)
  const { agentSlugs, catalog, errors, itemsByName } =
    await buildRegistry(agentsDir)
  const codeowners = buildCodeowners(itemsByName, FALLBACK_OWNER)

  if (errors.length > 0) {
    process.stderr.write('Registry validation failed:\n')
    for (const error of errors) {
      process.stderr.write(`  - ${error}\n`)
    }
    process.exitCode = 1
    return
  }

  if (isCheckOnly) {
    const currentCodeowners = await readFileIfExists(codeownersPath)
    if (currentCodeowners !== codeowners) {
      process.stderr.write(
        '.github/CODEOWNERS is out of date. Run "pnpm --filter @evex/agent-registry generate".\n',
      )
      process.exitCode = 1
      return
    }

    process.stdout.write(`Registry OK: ${agentSlugs.length} agents validated.\n`)
    return
  }

  // Write in place instead of wiping the directory first: turbo can run other
  // tasks (typecheck, dev) while this executes, and a delete-then-rewrite
  // window would make `../generated/items` unresolvable mid-generation.
  const itemsDir = path.join(generatedDir, 'items')
  await fs.mkdir(itemsDir, { recursive: true })

  await fs.writeFile(path.join(generatedDir, 'catalog.json'), stringify(catalog))
  for (const [slug, item] of Object.entries(itemsByName)) {
    await fs.writeFile(path.join(itemsDir, `${slug}.json`), stringify(item))
  }
  await fs.writeFile(
    path.join(generatedDir, 'items.ts'),
    createLoaderIndex(agentSlugs),
  )

  // Prune item files for agents that no longer exist.
  const expectedItemFiles = new Set(
    agentSlugs.map((slug) => `${slug}.json`),
  )
  for (const existingFile of await fs.readdir(itemsDir)) {
    if (!expectedItemFiles.has(existingFile)) {
      await fs.rm(path.join(itemsDir, existingFile), { force: true })
    }
  }

  // The committed CODEOWNERS is only written on explicit `generate`
  // (--codeowners). Install and build write the gitignored artifacts only:
  // if a lifecycle hook silently fixed the working tree, CI's freshness
  // check would pass while the committed file stayed stale.
  if (writeCodeowners) {
    await fs.writeFile(codeownersPath, codeowners)
    process.stdout.write(
      `Generated ${agentSlugs.length} registry items and .github/CODEOWNERS.\n`,
    )
    return
  }

  process.stdout.write(`Generated ${agentSlugs.length} registry items.\n`)
}

await main()
